/**
 * Provides shared env types and utilities for the application.
 */

import "server-only";
import { z } from "zod";

const envSchema = z.object({
  NEXT_PUBLIC_SITE_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_SITE_INDEXABLE: z.enum(["true", "false"]).default("false"),
  DATABASE_URL: z.preprocess((value) => value === "" ? undefined : value, z.string().min(1).optional()),
  DIRECT_URL: z.preprocess((value) => value === "" ? undefined : value, z.string().min(1).optional()),
  SQUARE_ENVIRONMENT: z.enum(["sandbox", "production"]).default("sandbox"),
  SQUARE_ALLOW_PRODUCTION_READONLY_SYNC: z.enum(["true", "false"]).default("false"),
  SQUARE_CHECKOUT_ENABLED: z.enum(["true", "false"]).default("false"),
  SQUARE_ACCESS_TOKEN: z.string().optional(),
  SQUARE_APPLICATION_ID: z.string().optional(),
  NEXT_PUBLIC_SQUARE_APPLICATION_ID: z.string().optional(),
  NEXT_PUBLIC_SQUARE_LOCATION_ID: z.string().optional(),
  SQUARE_WEBHOOK_SIGNATURE_KEY: z.string().optional(),
  WEBHOOK_WORKER_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  SHIPPO_API_TOKEN: z.string().optional(),
  SHIPPO_TEST_MODE: z.enum(["true", "false"]).default("true"),
  SHIPPO_ALLOWED_CARRIERS: z.string().optional(),
  SHIPPO_ALLOWED_RETURN_CARRIERS: z.string().optional(),
  SHIPPO_DEFAULT_RETURN_SERVICE: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_NAME: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_LINE1: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_LINE2: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_CITY: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_STATE: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_ZIP: z.string().optional(),
  SHIPPO_RETURN_ADDRESS_COUNTRY: z.string().optional(),
  SHIPPO_WEBHOOK_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  SHIPPO_PILOT_VARIATION_IDS: z.string().optional(),
  SHIPPO_ORIGIN_NAME: z.string().optional(),
  SHIPPO_ORIGIN_COMPANY: z.string().optional(),
  SHIPPO_ORIGIN_STREET1: z.string().optional(),
  SHIPPO_ORIGIN_CITY: z.string().optional(),
  SHIPPO_ORIGIN_STATE: z.string().optional(),
  SHIPPO_ORIGIN_ZIP: z.string().optional(),
  SHIPPO_ORIGIN_PHONE: z.string().optional(),
  SHIPPO_ORIGIN_EMAIL: z.string().optional(),
  SHIPPO_PILOT_LENGTH_IN: z.string().optional(),
  SHIPPO_PILOT_WIDTH_IN: z.string().optional(),
  SHIPPO_PILOT_HEIGHT_IN: z.string().optional(),
  SHIPPO_PILOT_WEIGHT_LB: z.string().optional(),
  MAPBOX_ACCESS_TOKEN: z.string().optional(),
  SENTRY_DSN: z.string().optional(),
  ADMIN_SESSION_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  ADMIN_LOGIN_EMAIL: z.preprocess((value) => value === "" ? undefined : value, z.string().email().optional()),
  ADMIN_PASSWORD_HASH: z.preprocess((value) => value === "" ? undefined : value, z.string().startsWith("scrypt-v1$").optional()),
  ADMIN_ALLOWED_ORIGINS: z.string().optional(),
  ADMIN_DEV_BYPASS: z.enum(["true", "false"]).default("false"),
  ORDERPRO_ADMIN_URL: z.preprocess((value) => value === "" ? undefined : value, z.string().url().optional()),
  ORDERPRO_M2M_AUTH_MODE: z.string().optional(),
  ORDERPRO_INTEGRATION_ENVIRONMENT: z.string().optional(),
  ORDERPRO_API_BASE_URL: z.string().optional(),
  ORDERPRO_AUTH0_ISSUER: z.string().optional(),
  ORDERPRO_AUTH0_AUDIENCE: z.string().optional(),
  ORDERPRO_AUTH0_CLIENT_ID: z.string().optional(),
  ORDERPRO_AUTH0_CLIENT_SECRET: z.string().optional(),
  ORDERPRO_AUTH0_SCOPES: z.string().optional(),
  ORDERPRO_STOREFRONT_PREVIEW_BASE_URL: z.preprocess((value) => value === "" ? undefined : value, z.string().url().optional()),
  ORDERPRO_STOREFRONT_PREVIEW_SHARED_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  ORDERPRO_STOREFRONT_SHIPPING_SHARED_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  ORDERPRO_STOREFRONT_RETURNS_SHARED_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  ORDERPRO_RETURNS_ENABLED: z.enum(["true", "false"]).default("false"),
  RETURNS_SESSION_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  RETURNS_BUSINESS_TIME_ZONE: z.string().default("America/New_York"),
  SQUARE_RETURNS_REFUNDS_ENABLED: z.enum(["true", "false"]).default("false"),
  ORDERPRO_LOCAL_DELIVERY_CHECKOUT_ENABLED: z.string().optional(),
  ORDERPRO_SHIPPING_CHECKOUT_ENABLED: z.string().optional(),
  ALLOW_LOCAL_PERSISTENCE_FALLBACK: z.enum(["true", "false"]).default("false"),
  CUSTOMER_SESSION_SECRET: z.preprocess((value) => value === "" ? undefined : value, z.string().min(32).optional()),
  CUSTOMER_AUTH_DEV_PREVIEW: z.enum(["true", "false"]).default("true"),
  RESEND_API_KEY: z.preprocess((value) => value === "" ? undefined : value, z.string().min(1).optional()),
  CUSTOMER_AUTH_EMAIL_FROM: z.preprocess((value) => value === "" ? undefined : value, z.string().min(3).optional())
});

export const env = envSchema.parse(process.env);
