/**
 * Defines the store section registry configuration used by the application.
 */

export type StoreSectionRegistryEntry = {
  sectionId: string;
  area: string;
  sectionName: string;
  description: string;
  customerFacing: boolean;
  adminEditable: "Yes" | "No" | "Partially";
  editableFields: string[];
  relatedFiles: string[];
  doNotEditHere: string[];
  businessLogicFiles: string[];
  riskLevel: "low" | "medium" | "high" | "critical";
};

export const storeSectionRegistry: StoreSectionRegistryEntry[] = [
  {
    sectionId: "home.hero",
    area: "Homepage",
    sectionName: "Homepage Hero",
    description: "First viewport brand, positioning, and primary shopping path.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["eyebrow", "title", "body", "ctaLabel", "ctaHref", "heroImage"],
    relatedFiles: ["src/features/homepage/config/homepage.config.ts", "src/features/homepage/components/homepage-template.tsx"],
    doNotEditHere: ["Square catalog data", "checkout rules", "delivery fees"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "home.departments",
    area: "Homepage",
    sectionName: "Department Grid",
    description: "Homepage gateway into first-class website departments.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["department visibility", "sort order", "hero copy", "accent color"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/department-card-grid.tsx"],
    doNotEditHere: ["Square reporting_category", "Square categories"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "home.featured-products",
    area: "Homepage",
    sectionName: "Featured Products",
    description: "Configurable product merchandising rail backed by Square cache and website overrides.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["product assignments", "badges", "sort order", "visibility"],
    relatedFiles: ["src/features/homepage/config/homepage.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["price overrides without approval", "inventory counts"],
    businessLogicFiles: ["src/server/square/catalog-postgres-sync.ts", "src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "home.balloon-promo",
    area: "Homepage",
    sectionName: "Balloon Promotion",
    description: "Homepage entry into guided balloon buying.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "cta", "featured balloon flows"],
    relatedFiles: ["src/config/balloons.config.ts", "src/components/templates/balloons-page-template.tsx"],
    doNotEditHere: ["slot capacity", "delivery zones", "Square payment logic"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts", "src/features/fulfillment/services/slot-capacity-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "home.party-supplies-callout",
    area: "Homepage",
    sectionName: "Party Supplies Callout",
    description: "Compact homepage call to action for the party supplies department.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["visibility", "eyebrow", "title", "body", "cta", "image"],
    relatedFiles: [
      "src/features/homepage/config/homepage.config.ts",
      "src/features/homepage/components/homepage-party-supplies-card.tsx"
    ],
    doNotEditHere: ["catalog prices", "inventory counts", "checkout rules"],
    businessLogicFiles: [],
    riskLevel: "low"
  },
  {
    sectionId: "home.featured-brands-carousel",
    area: "Homepage",
    sectionName: "Featured Brands Carousel",
    description: "Compact horizontal carousel of Catalog Publishing brands selected for the homepage.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["visibility", "title", "brand assignments", "brand order"],
    relatedFiles: [
      "src/features/homepage/config/homepage.config.ts",
      "src/features/homepage/components/homepage-featured-brands-carousel.tsx"
    ],
    doNotEditHere: ["catalog product prices", "inventory counts"],
    businessLogicFiles: [],
    riskLevel: "low"
  },
  {
    sectionId: "home.local-storefront",
    area: "Homepage",
    sectionName: "Local Storefront",
    description: "Store pickup and neighborhood delivery positioning.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["location highlights", "store hours after verification"],
    relatedFiles: ["src/config/locations.config.ts", "src/components/templates/locations-page-template.tsx"],
    doNotEditHere: ["delivery zone polygon math", "slot reservations"],
    businessLogicFiles: ["src/features/locations/services/location-service.ts", "src/features/fulfillment/services/delivery-zone-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "toys.hero",
    area: "Toys",
    sectionName: "Toys Hero",
    description: "Toys department hero, SEO, and merchandising setup.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["title", "description", "SEO", "hero images", "accent"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/toys/page.tsx"],
    doNotEditHere: ["Square categories", "Square reporting_category"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "toys.product-grid",
    area: "Toys",
    sectionName: "Toys Product Grid",
    description: "Toys product assignment and grid preset.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "badges", "grid preset"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["prices", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "party-supplies.hero",
    area: "Party Supplies",
    sectionName: "Party Supplies Hero",
    description: "Party department intro and SEO.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["title", "description", "SEO", "hero images", "accent"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/party-supplies/page.tsx"],
    doNotEditHere: ["Square categories", "slot capacity"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "party-supplies.event-types",
    area: "Party Supplies",
    sectionName: "Party Event Types",
    description: "Birthday, graduation, baby shower, wedding, and sports party entry points.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["event labels", "event product assignments", "sort order"],
    relatedFiles: ["src/components/templates/department-page-template.tsx"],
    doNotEditHere: ["Square reporting"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "party-supplies.product-grid",
    area: "Party Supplies",
    sectionName: "Party Supplies Product Grid",
    description: "Party product merchandising grid.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "grid preset"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["Square pricing", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "balloons.landing-hero",
    area: "Balloons",
    sectionName: "Balloons Landing Hero",
    description: "Balloons overview and guided builder entry point.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "hero images", "featured flows"],
    relatedFiles: ["src/config/balloons.config.ts", "src/app/(store)/balloons/page.tsx"],
    doNotEditHere: ["Square order creation", "slot locking"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "balloons.builder",
    area: "Balloons",
    sectionName: "Balloon Builder",
    description: "Guided selection of balloon type, colors, add-ons, fulfillment, and time slot.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["builder options", "templates", "eligible add-ons", "capacity points"],
    relatedFiles: ["src/config/balloons.config.ts", "src/components/templates/balloons-page-template.tsx"],
    doNotEditHere: ["payment tokens", "Square access tokens"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts", "src/features/fulfillment/services/slot-capacity-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "balloons.occasion-selector",
    area: "Balloons",
    sectionName: "Occasion Selector",
    description: "Editable occasion choices for balloon orders.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["occasion labels", "sort order", "visibility"],
    relatedFiles: ["src/config/balloons.config.ts"],
    doNotEditHere: ["price calculations"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "balloons.type-selector",
    area: "Balloons",
    sectionName: "Type Selector",
    description: "Latex, mylar, number, letter, and bouquet selection.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["types", "Square variation mapping", "visibility"],
    relatedFiles: ["src/config/balloons.config.ts"],
    doNotEditHere: ["inventory deduction logic"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts", "src/server/square/catalog-postgres-sync.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "balloons.color-selector",
    area: "Balloons",
    sectionName: "Color Selector",
    description: "Color and style choices for balloon components.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["colors", "stock mapping", "sort order"],
    relatedFiles: ["src/config/balloons.config.ts"],
    doNotEditHere: ["Square inventory count edits"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "balloons.addons-selector",
    area: "Balloons",
    sectionName: "Add-ons Selector",
    description: "Weights, ribbons, custom notes, and presentation options.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["add-ons", "stocked/non-stocked modeling", "sort order"],
    relatedFiles: ["src/config/balloons.config.ts"],
    doNotEditHere: ["card/payment data"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "balloons.fulfillment-selector",
    area: "Balloons",
    sectionName: "Fulfillment Selector",
    description: "Store pickup and local delivery selection for balloon orders.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["eligible modes", "copy"],
    relatedFiles: ["src/components/templates/balloons-page-template.tsx"],
    doNotEditHere: ["zone validation", "delivery fees", "slot locks"],
    businessLogicFiles: ["src/features/fulfillment/services/delivery-zone-service.ts", "src/features/fulfillment/services/slot-capacity-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "balloons.time-slot-picker",
    area: "Balloons",
    sectionName: "Time Slot Picker",
    description: "Pickup and local delivery slot selection backed by temporary holds and capacity points.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["slot templates", "capacity points", "cutoff windows"],
    relatedFiles: ["src/components/templates/balloons-page-template.tsx"],
    doNotEditHere: ["client-side capacity trust"],
    businessLogicFiles: ["src/features/fulfillment/services/slot-capacity-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "stationery.hero",
    area: "Stationery",
    sectionName: "Stationery Hero",
    description: "Stationery department hero and SEO.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "SEO", "hero images"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/stationery/page.tsx"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "stationery.product-grid",
    area: "Stationery",
    sectionName: "Stationery Product Grid",
    description: "Stationery product merchandising.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "visibility"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["prices", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "arts-crafts.hero",
    area: "Arts & Crafts",
    sectionName: "Arts & Crafts Hero",
    description: "Arts and crafts department hero and SEO.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "SEO", "hero images"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/arts-and-crafts/page.tsx"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "arts-crafts.product-grid",
    area: "Arts & Crafts",
    sectionName: "Arts & Crafts Product Grid",
    description: "Arts and crafts product merchandising.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "visibility"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["prices", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "greeting-cards.hero",
    area: "Greeting Cards",
    sectionName: "Greeting Cards Hero",
    description: "Greeting cards department hero and SEO.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "SEO", "hero images"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/greeting-cards/page.tsx"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "greeting-cards.occasion-grid",
    area: "Greeting Cards",
    sectionName: "Greeting Card Occasion Grid",
    description: "Occasion-led navigation for greeting cards.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["occasion labels", "assigned products", "sort order"],
    relatedFiles: ["src/components/templates/department-page-template.tsx"],
    doNotEditHere: ["Square reporting"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "gifts.hero",
    area: "Gifts",
    sectionName: "Gifts Hero",
    description: "Gifts department hero and SEO.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "SEO", "hero images"],
    relatedFiles: ["src/config/departments.config.ts", "src/app/(store)/gifts/page.tsx"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "gifts.product-grid",
    area: "Gifts",
    sectionName: "Gifts Product Grid",
    description: "Gifts product merchandising.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "visibility"],
    relatedFiles: ["src/config/departments.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["prices", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "holidays.index-hero",
    area: "Holidays",
    sectionName: "Holidays Index Hero",
    description: "Editable parent page for active and upcoming holidays.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["copy", "hero images", "accent"],
    relatedFiles: ["src/config/holidays.config.ts", "src/app/(store)/holidays/page.tsx"],
    doNotEditHere: ["individual holiday products"],
    businessLogicFiles: ["src/features/holidays/services/holiday-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "holidays.active-holidays-grid",
    area: "Holidays",
    sectionName: "Active Holidays Grid",
    description: "Visible holiday cards and merchandising order.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["active state", "visibility", "dates", "sort order"],
    relatedFiles: ["src/config/holidays.config.ts"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/holidays/services/holiday-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "holidays.detail-hero",
    area: "Holidays",
    sectionName: "Holiday Detail Hero",
    description: "Holiday detail page hero, SEO, and campaign copy.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["copy", "SEO", "hero image", "accent", "dates"],
    relatedFiles: ["src/config/holidays.config.ts", "src/app/(store)/holidays/[slug]/page.tsx"],
    doNotEditHere: ["Square reporting"],
    businessLogicFiles: ["src/features/holidays/services/holiday-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "holidays.detail-product-grid",
    area: "Holidays",
    sectionName: "Holiday Product Grid",
    description: "Holiday-specific product assignment and grid layout.",
    customerFacing: true,
    adminEditable: "Yes",
    editableFields: ["assigned products", "sort order", "badges", "visibility"],
    relatedFiles: ["src/config/holidays.config.ts", "src/components/commerce/product-card.tsx"],
    doNotEditHere: ["prices", "inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "cart.drawer",
    area: "Cart",
    sectionName: "Cart Drawer",
    description: "Cart preview and item quantity controls.",
    customerFacing: true,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/app/(checkout)/cart/page.tsx", "src/components/checkout/cart-page-template.tsx"],
    doNotEditHere: ["price trust", "inventory trust"],
    businessLogicFiles: ["src/server/checkout/cart-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "cart.order-summary",
    area: "Cart",
    sectionName: "Cart Order Summary",
    description: "Validated cart totals before checkout.",
    customerFacing: true,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/components/checkout/cart-page-template.tsx"],
    doNotEditHere: ["payment processing"],
    businessLogicFiles: ["src/server/checkout/cart-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "checkout.customer-info",
    area: "Checkout",
    sectionName: "Customer Information",
    description: "Customer contact and order ownership fields.",
    customerFacing: true,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/app/(checkout)/checkout/page.tsx", "src/components/checkout/checkout-page-template.tsx"],
    doNotEditHere: ["payment tokens"],
    businessLogicFiles: ["src/server/checkout/checkout-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "checkout.fulfillment",
    area: "Checkout",
    sectionName: "Fulfillment Selection",
    description: "Pickup, local delivery, or shipping group selection.",
    customerFacing: true,
    adminEditable: "Partially",
    editableFields: ["eligible modes by product", "copy"],
    relatedFiles: ["src/components/checkout/checkout-page-template.tsx"],
    doNotEditHere: ["client-trusted fees", "client-trusted slots"],
    businessLogicFiles: ["src/server/fulfillment/fulfillment-router.ts", "src/server/shipping/shipping-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "checkout.payment",
    area: "Checkout",
    sectionName: "Square Payment",
    description: "Square Web Payments tokenization and server-side Square Payments API processing.",
    customerFacing: true,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/components/checkout/checkout-page-template.tsx"],
    doNotEditHere: ["raw card fields", "Square access tokens"],
    businessLogicFiles: ["src/server/square/client.ts", "src/server/checkout/checkout-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "checkout.order-summary",
    area: "Checkout",
    sectionName: "Checkout Order Summary",
    description: "Final validated order summary.",
    customerFacing: true,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/components/checkout/checkout-page-template.tsx"],
    doNotEditHere: ["payment capture", "inventory edits"],
    businessLogicFiles: ["src/server/checkout/checkout-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.control-plane",
    area: "Admin",
    sectionName: "Admin Control Plane",
    description: "Production control center for storefront, catalog, operations, settings, and publish workflow.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["module drafts", "publish workflow", "release notes", "production readiness"],
    relatedFiles: ["src/app/(admin)/admin/page.tsx", "src/components/admin/admin-dashboard.tsx", "src/config/admin-control-plane.ts"],
    doNotEditHere: ["payment secrets", "Square access tokens", "raw card data"],
    businessLogicFiles: ["src/server/admin/admin-control-plane-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.homepage-sections",
    area: "Admin",
    sectionName: "Homepage Sections Manager",
    description: "Controlled admin editor for homepage modules.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["homepage section content through admin UI"],
    relatedFiles: ["src/app/(admin)/admin/homepage/page.tsx", "src/components/admin/admin-page-shell.tsx"],
    doNotEditHere: ["arbitrary CSS", "Square catalog mutations"],
    businessLogicFiles: ["src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.departments",
    area: "Admin",
    sectionName: "Department Manager",
    description: "Admin management for website departments independent from Square categories.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["department copy", "SEO", "visibility", "product assignments"],
    relatedFiles: ["src/app/(admin)/admin/departments/page.tsx"],
    doNotEditHere: ["Square reporting_category"],
    businessLogicFiles: ["src/features/departments/services/department-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.navigation",
    area: "Admin",
    sectionName: "Navigation Manager",
    description: "No-code editor for navigation labels, order, visibility, and campaign links.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["navigation labels", "sort order", "visibility", "links"],
    relatedFiles: ["src/app/(admin)/admin/navigation/page.tsx", "src/config/header-navigation.config.ts"],
    doNotEditHere: ["security headers", "auth routes", "Square categories"],
    businessLogicFiles: ["src/features/admin/services/cms-workflow-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.holidays",
    area: "Admin",
    sectionName: "Holiday Manager",
    description: "Admin management for editable holiday campaigns.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["holiday copy", "dates", "SEO", "visibility", "product assignments"],
    relatedFiles: ["src/app/(admin)/admin/holidays/page.tsx"],
    doNotEditHere: ["Square categories"],
    businessLogicFiles: ["src/features/holidays/services/holiday-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.product-placement-manager",
    area: "Admin",
    sectionName: "Product Placement Manager",
    description: "Flexible website placement system for Square products across departments, holidays, balloons, homepage, groups, search, and promos.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["placement target", "section", "sort order", "featured", "visibility", "schedule"],
    relatedFiles: ["src/app/(admin)/admin/product-placement/page.tsx", "src/components/admin/product-placement-manager.tsx"],
    doNotEditHere: ["Square reporting_category", "Square categories", "Square prices", "Square inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-placement-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.product-display",
    area: "Admin",
    sectionName: "Product Display",
    description: "Website-only product title, short description, full description, badges, status, card style, and visibility editor.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["web title", "web short description", "web full description", "badge", "status", "card style", "visibility"],
    relatedFiles: ["src/app/(admin)/admin/product-display/page.tsx"],
    doNotEditHere: ["Square item name", "Square price", "Square inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-description-service.ts", "src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.product-seo",
    area: "Admin",
    sectionName: "Product SEO",
    description: "Website-only SEO metadata, Open Graph image, canonical URL, keywords, and internal tags.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["SEO title", "SEO description", "Open Graph image", "canonical URL", "keywords", "internal tags"],
    relatedFiles: ["src/app/(admin)/admin/product-seo/page.tsx"],
    doNotEditHere: ["Square catalog metadata writes"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.product-images",
    area: "Admin",
    sectionName: "Product Images",
    description: "Local website image ordering and display settings for Square-imported images.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["primary image", "gallery order", "hide from website", "alt text", "card image", "detail image"],
    relatedFiles: ["src/app/(admin)/admin/product-images/page.tsx", "src/config/store-section-registry.ts"],
    doNotEditHere: ["Square image ordering", "Square image deletion"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.media-library",
    area: "Admin",
    sectionName: "Media Library",
    description: "No-code media asset management for homepage, department, holiday, and product presentation.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["asset URL", "alt text", "visibility", "usage"],
    relatedFiles: ["src/app/(admin)/admin/media-library/page.tsx"],
    doNotEditHere: ["payment assets", "secret files"],
    businessLogicFiles: ["src/server/admin/admin-audit-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "admin.users-roles",
    area: "Admin",
    sectionName: "Users and Roles",
    description: "Role-based permissions for owner, manager, store staff, delivery staff, warehouse staff, and viewer.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["user role", "location scope", "MFA readiness", "active status"],
    relatedFiles: ["src/app/(admin)/admin/users-roles/page.tsx"],
    doNotEditHere: ["password handling internals", "session secret", "payment tokens"],
    businessLogicFiles: ["src/server/admin/admin-security.ts", "src/server/admin/admin-audit-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.delivery-zones",
    area: "Admin",
    sectionName: "Delivery Zone Editor",
    description: "Map-based editable delivery zones stored as GeoJSON/PostGIS polygons.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["polygons", "fees", "cutoffs", "lead times", "service mode"],
    relatedFiles: ["src/app/(admin)/admin/delivery-zones/page.tsx"],
    doNotEditHere: ["frontend-only zone validation"],
    businessLogicFiles: ["src/features/fulfillment/services/delivery-zone-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.pickup-slots",
    area: "Admin",
    sectionName: "Pickup and Delivery Slots",
    description: "Read-only handoff to the OrderPro availability source of truth.",
    customerFacing: false,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/app/(admin)/admin/slots/page.tsx"],
    doNotEditHere: ["OrderPro slot windows", "OrderPro capacity", "client-side capacity trust"],
    businessLogicFiles: ["src/server/orderpro"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.balloon-builder",
    area: "Admin",
    sectionName: "Balloon Builder Manager",
    description: "Admin management for balloon components and templates.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["components", "templates", "add-ons", "capacity points"],
    relatedFiles: ["src/app/(admin)/admin/balloons/page.tsx"],
    doNotEditHere: ["payment handling"],
    businessLogicFiles: ["src/features/balloons/services/balloon-builder-service.ts"],
    riskLevel: "critical"
  },
  {
    sectionId: "admin.product-overrides",
    area: "Admin",
    sectionName: "Product Overrides",
    description: "Website-only product SEO, visibility, badges, and display overrides.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["web visibility", "SEO", "badges", "display copy"],
    relatedFiles: ["src/app/(admin)/admin/product-overrides/page.tsx"],
    doNotEditHere: ["Square prices", "Square inventory"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "high"
  },
  {
    sectionId: "admin.image-settings",
    area: "Admin",
    sectionName: "Product Image Settings",
    description: "Website product image ordering and display preferences.",
    customerFacing: false,
    adminEditable: "Yes",
    editableFields: ["primary image", "image order", "alt text", "display crop"],
    relatedFiles: ["src/app/(admin)/admin/product-overrides/page.tsx"],
    doNotEditHere: ["Square image deletion"],
    businessLogicFiles: ["src/features/catalog/services/product-display-service.ts"],
    riskLevel: "medium"
  },
  {
    sectionId: "admin.fulfillment-dashboard",
    area: "Admin",
    sectionName: "Fulfillment Dashboard",
    description: "Read-only handoff to OrderPro for orders and fulfillment queues.",
    customerFacing: false,
    adminEditable: "No",
    editableFields: [],
    relatedFiles: ["src/app/(admin)/admin/fulfillment/page.tsx"],
    doNotEditHere: ["OrderPro orders", "OrderPro status transitions", "customer card data", "Square secrets"],
    businessLogicFiles: ["src/server/orderpro"],
    riskLevel: "critical"
  }
];

export function getStoreSection(sectionId: string) {
  return storeSectionRegistry.find((section) => section.sectionId === sectionId);
}
